  project:
    type: website
    output-dir: docs

  website:
    title: "Conner M. Hale"
    navbar:
      left:
	- href: mainpage.qmd
          text: Conner M. Hale
        - href: experience.qmd
          text: Experience
        - href: pubs.qmd
          text: Publications
    search: false
      
  format:
    html:
      mainfont: Gill Sans
      theme: pulse
      css: styles.css
      toc: true
      
  editor: visual